---
title: "D-cellerate Reproduceable Report"
author: "D-cellerate"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: united
    code_folding: show
params:
  import.params: NA
  filter.params: NA
  pca.params: NA
  cluster.params: NA
  cluster.renamed.params: NA
  tsne.params: NA
  marker.params: NA
  markers.params: NA
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.align = "center")
```

<br>

---

<br>

# Load required packages

```{r}
library(knitr)
library(Seurat)
library(Matrix)
#require("stringr")
```

<br>

---

<br>

# Import Data

```{r}
#-- import.params
```

<!-- #import.fun -->

```{r eval=FALSE, include=FALSE}
dim(mat)
```

<br>

This data set contains `r dim(mat)[1]` genes and `r dim(mat)[2]` cells.

<br>

---

<br>

# Filter

```{r}
#-- filter.params
```

<!-- #filter.fun -->

```{r eval=FALSE, include=FALSE}
dim(sobj)
```


<br>  

The filtered data set contains `r dim(sobj)[1]` genes and `r dim(sobj)[2]` cells. 

<!-- #barcode.plot.fun -->

<!-- #violin.plot.fun -->



<br>

---

<br>

# Normalize

```{r}
#-- normalize.params
```

<!-- #normalize.fun -->

<!-- #normalize.histogram.fun -->

<br>

---

<br>

# Variable genes

```{r}
#-- vargenes.params
```

<!-- #vargenes.fun -->

<!-- #vargenes.plot.fun -->

<br>

---

<br>

# PCA

```{r}
#-- pca.params
```

<!-- #scale.fun -->

<!-- #pca.fun -->

<!-- #pca.scree.plot.fun -->

```{r}
dim1 <- 1; dim2 <- 2; dim3 <- 3
```

<!-- #pca.plot.fun -->

<br>

---

<br>

# Clustering



```{r}
#-- cluster.params
```

<!-- #cluster.fun -->

```{r}
#-- cluster.renamed.params
```

<!-- #cluster.renamed.fun -->


<br>

---

<br>

# Dimensional Reduction

```{r}
#-- tsne.params
```

<!-- #tsne.fun -->

```{r}
DimPlot(sobj, reduction = "tsne", label = TRUE)
```


<!-- plot.tsne.fun -->



<br>

---

<br>

# Marker Gene Identification

```{r}
#-- marker.params
marker.params$genes <- strsplit(stringr::str_replace_all(marker.params$genes, 
                                                         "c\\(|[^[A-Za-z0-9,]]", ""), ",")[[1]] # parse genes 
marker.params$top.marker.genes <- strsplit(stringr::str_replace_all(marker.params$top.marker.genes, 
                                                         "c\\(|[^[A-Za-z0-9,-]]", ""), ",")[[1]] # parse genes 
```

<!-- #top.markers.fun -->

<!-- #marker.plot.fun -->

<br>

---

<br>

# Session Info

```{r}
sessionInfo()
```



